# Generated by Django 4.0 on 2022-08-23 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0033_alter_userinfo_phone_alter_userinfo_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FeeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userinfo')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('signed_amount', models.FloatField()),
                ('is_credit', models.BooleanField(default=False)),
                ('is_debit', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.account')),
                ('fee_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.feesubmission')),
            ],
        ),
    ]
