# Generated by Django 4.0 on 2022-08-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_requestconfirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feesubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='RequestConfirmation',
        ),
    ]
