# Generated by Django 4.0 on 2022-08-23 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_userinfo_phone_alter_userinfo_profile_picture_and_more'),
        ('payment', '0003_alter_feesubmission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userinfo')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
