# Generated by Django 4.0 on 2022-08-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_requestconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestconfirmation',
            name='is_expired',
        ),
    ]
