# Generated by Django 4.0 on 2022-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_requestconfirmation_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesubmission',
            name='card',
            field=models.ImageField(default='cards/test-card.jpg', upload_to='cards'),
        ),
    ]
