# Generated by Django 4.0 on 2022-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_feesubmission_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestconfirmation',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
