# Generated by Django 4.0 on 2022-08-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_account_account_id_transaction_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_id',
            new_name='acc_id',
        ),
    ]
