# Generated by Django 4.0 on 2022-08-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_rename_account_id_account_acc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='acc_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
