# Generated by Django 4.0 on 2022-08-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_account_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created_at',)},
        ),
    ]
