# Generated by Django 4.0 on 2022-08-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('stripe_cust_id', models.CharField(max_length=60)),
                ('ephemeral_key', models.CharField(max_length=60)),
                ('payment_intent', models.CharField(max_length=60)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
