# Generated by Django 3.0.8 on 2022-01-27 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('icon', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('cat_id',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.Category')),
            ],
            options={
                'ordering': ('course_id',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('tagline', models.CharField(max_length=70)),
                ('display_pic', models.ImageField(default='levels/default-display.jpg', upload_to='levels')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.Course')),
            ],
            options={
                'ordering': ('level_id',),
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('mission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('display_pic', models.ImageField(default='missions/default-display.jpg', upload_to='missions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='api.Level')),
            ],
            options={
                'ordering': ('mission_id',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subs_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('sales_tax', models.IntegerField(default=9)),
                ('freq', models.CharField(choices=[('month', 'monthly'), ('year', 'yearly'), ('week', 'weekly')], max_length=20)),
                ('ft_days', models.IntegerField()),
                ('is_best', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Currency')),
            ],
            options={
                'ordering': ('subs_id',),
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/default-profile.png', null=True, upload_to='avatars')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
                ('video_url', models.FileField(upload_to='videos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='api.Mission')),
            ],
            options={
                'ordering': ('video_id',),
            },
        ),
        migrations.CreateModel(
            name='UnlockedMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SystemUser')),
            ],
        ),
        migrations.CreateModel(
            name='UnlockedLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SystemUser')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SystemUser')),
            ],
        ),
    ]
