# Generated by Django 3.0.8 on 2022-01-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220128_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='trial_id',
            new_name='id',
        ),
    ]
