# Generated by Django 3.0.8 on 2022-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220128_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='stripe_cust_id',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
