# Generated by Django 3.0.8 on 2022-01-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220128_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='stripe_cust_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
