# Generated by Django 3.0.8 on 2022-01-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_systemuser_stripe_cust_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='stripe_cust_id',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='uid',
        ),
    ]
