# Generated by Django 3.0.8 on 2022-01-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220128_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unlockedlevel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unlockedmission',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
