# Generated by Django 3.0.8 on 2022-01-28 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='is_trial_synced',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
