# Generated by Django 3.0.8 on 2022-01-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220128_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('pay_id',)},
        ),
        migrations.AddField(
            model_name='systemuser',
            name='is_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='is_trial_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='is_trial_taken',
            field=models.BooleanField(default=False),
        ),
    ]
