# Generated by Django 3.0.8 on 2022-02-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220130_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available_on_free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
