# Generated by Django 3.0.8 on 2022-02-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_completedcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unlockedmission',
            options={'ordering': ('pk',)},
        ),
    ]
