# Generated by Django 3.0.8 on 2022-02-25 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220225_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SystemUser')),
            ],
        ),
    ]
