# Generated by Django 3.2.9 on 2022-03-05 08:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0024_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuttle_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
        ),
    ]
