# Generated by Django 3.2.9 on 2022-03-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0002_shuttle_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shuttle',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
