# Generated by Django 3.2.9 on 2022-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile-pictures/drivers/default-dp.png', null=True, upload_to='profile-pictures/drivers'),
        ),
    ]
