# Generated by Django 3.2.9 on 2022-03-04 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='driver',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
