# Generated by Django 3.2.9 on 2022-03-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20220304_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='profile_picture',
        ),
    ]
