# Generated by Django 3.2.9 on 2022-03-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20220304_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
