# Generated by Django 3.2.9 on 2022-03-04 14:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import drivers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0024_delete_driver'),
        ('drivers', '0005_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='profile-pictures/drivers/default-dp.png', null=True, upload_to='profile-pictures/drivers')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('pin', models.CharField(max_length=4, validators=[drivers.models.only_int, django.core.validators.MinLengthValidator(4)])),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
