# Generated by Django 3.2.9 on 2022-03-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
    ]
