# Generated by Django 2.2.10 on 2021-08-14 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20210814_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Position',
        ),
    ]
