# Generated by Django 2.2.10 on 2021-08-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210815_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url_name', models.CharField(max_length=50)),
                ('template', models.CharField(max_length=50)),
                ('context', models.ManyToManyField(to='dashboard.DataField')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='pages',
            field=models.ManyToManyField(to='dashboard.Page'),
        ),
    ]
