# Generated by Django 2.2.10 on 2021-08-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210815_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='context',
            field=models.ManyToManyField(null=True, to='dashboard.DataField'),
        ),
    ]
