# Generated by Django 2.2.10 on 2021-08-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210815_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
