# Generated by Django 2.2.10 on 2021-08-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210815_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='abbr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
