# Generated by Django 2.2.10 on 2021-08-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210815_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='context',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.DataField'),
        ),
    ]
