# Generated by Django 2.2.10 on 2021-08-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210815_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
