# Generated by Django 2.2.10 on 2021-08-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210815_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='point_fee',
            field=models.FloatField(default=500),
        ),
    ]
