# Generated by Django 2.2.10 on 2021-08-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_organization_point_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.CharField(default='fas fa-fw fa-chart-area', max_length=50),
        ),
    ]
