# Generated by Django 2.2.10 on 2021-09-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_page_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_show_on_sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
