# Generated by Django 2.2.10 on 2021-09-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_page_is_show_on_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_parameters_included',
            field=models.BooleanField(default=False),
        ),
    ]
