# Generated by Django 3.2.9 on 2021-12-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
