# Generated by Django 3.2.9 on 2022-01-05 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_driver_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization'),
        ),
        migrations.AddField(
            model_name='point',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization'),
        ),
    ]
