# Generated by Django 3.2.9 on 2022-01-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20220105_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_address',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_cnic',
        ),
    ]
