# Generated by Django 3.2.9 on 2022-03-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20220108_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ('-created_at',)},
        ),
    ]
