# Generated by Django 3.2.9 on 2022-03-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20220304_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
