# Generated by Django 3.2.9 on 2022-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20220528_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, default='dp/default.jpg', null=True, upload_to='dp'),
        ),
    ]
