# Generated by Django 3.2.9 on 2022-07-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_userinfo_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_picture',
        ),
    ]
