# Generated by Django 3.2.9 on 2022-07-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_userinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='dp'),
        ),
    ]
