# Generated by Django 4.0 on 2022-07-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_userinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(default='profile.jpg', upload_to='dp'),
        ),
    ]
