# Generated by Django 4.0 on 2022-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_userinfo_phone_alter_userinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
