# Generated by Django 4.0 on 2022-08-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_userinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roll_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
