# Generated by Django 4.0 on 2022-08-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_userinfo_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='id_card_back_pic',
            field=models.ImageField(blank=True, null=True, upload_to='id-cards'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='id_card_front_pic',
            field=models.ImageField(blank=True, null=True, upload_to='id-cards'),
        ),
    ]
