# Generated by Django 4.0 on 2022-08-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_userinfo_id_card_back_pic_userinfo_id_card_front_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roll_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
