# Generated by Django 4.0 on 2022-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_userinfo_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='abbr',
            field=models.CharField(max_length=6),
        ),
    ]
