# Generated by Django 4.0 on 2022-08-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_department_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='stripe_cust_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
