# Generated by Django 4.0 on 2022-08-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_userinfo_stripe_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(blank=True, error_messages={'unique': 'User with this UID number already exists.'}, max_length=255, null=True, unique=True),
        ),
    ]
